### ISSUE TITLE
Breaks Media Queries Closing Indentation

### ISSUE THREAD

**Issue by ghost** [juancarlospaco/css-html-prettify#1]
``` css
@media (min-width:0) and (max-width:985px) {

    #example_selector {
        margin:0;
    }

}
```

Becomes:

``` css
@media (min-width:0) and (max-width:985px) {

    #example_selector {
        margin: 0;
}

}
```

Notice the `}` lost its indentation.
