### ISSUE TITLE
Semi-colon and sorting issue

### ISSUE THREAD

**Issue by Omniferum** [juancarlospaco/css-html-prettify#3]
Sorting issue referencing: css-html-js-minify [#16](https://github.com/juancarlospaco/css-html-js-minify/issues/16) - sorting randomizing issue is still present with this standalone package.

However using this gives extra semi-colons.

WITHOUT ARGUMENTS

``` css
a :hover {
        cursor:pointer;
;
}
```

WITH --GROUP ARGUMENT

``` css
a :hover {
;

        cursor:pointer;
}
```

**Comment by ghost** [comment]
This will not Remove Anything from the CSS, not even Empty lines or Semicolons.
Target is to Preserve always the CSS, just "Cosmetically" reorganize it making it more easy to read.

Why this is Ok :grey_question: 
Because some people writes CSS like...

``` scss

transition:
        max-height
        $animation-duration
        $animation-timing-function
        ;
;

```

Using `;` as kind of Closing Brackets or something like that, 
I dont use it, but still, they should be preserved. :poultry_leg:

**Comment by Omniferum** [comment]
It added the semi-colons, I've never had a CSS processor do that before or in that order before. The sorting issue however still stands.

**Comment by ghost** [comment]
Whats the ORIGINAL css ?

``` css
a :hover {
        cursor:pointer;
;
}
```

:grey_question:

**Comment by Omniferum** [comment]
``` css
a :hover {
        cursor:pointer;
}
```

**Comment by ghost** [comment]
Oh, now I understand!, ok its a Bug, hehe, will investigate it...   :pouting_cat:

**Comment by ghost** [comment]
**INPUT ORIGINAL CSS:**

``` css
a :hover {
    cursor:pointer;
}
.contactForm input[type=submit] {
    min-height: 40px;
    display: block;
    margin: 0 auto;
    margin-top: 1%;
}
.contactFullname, .contactEmail {
    margin: 0 auto;
    margin-bottom: 1%;
}
```

**OUTPUT PRETTY CSS:**

``` css
@charset utf-8;


a :hover {
    cursor:        pointer;
}

.contactForm input[type=submit] {
    display:       block;

    margin:        0 auto;
    margin-top:    1%;
    min-height:    40px;
}


.contactFullname, .contactEmail {
    margin:        0 auto;
    margin-bottom: 1%;
}

```

**COMMAND USED:**

```
python3 css-html-prettify.py --group --justify test.css
```

Where `test.css` was the filename of the original css.
Any other Details are welcome on a new Bug Report, this one seems solved.
Looking forward to integrate the Fixes on the CSS-HTML-JS-Minify.
Thank you very much @Omniferum :grey_exclamation: 

:octocat:
